### ISSUE TITLE
Crash when tracker attempts to click items

### ISSUE THREAD

**Issue by Datyedyeguy** [gameboy9/randoTracker#38]
Reported by OPTLayer during the quad DW4 race that occurred tonight.

[Tracker_Error.txt](https://github.com/gameboy9/randoTracker/files/1783549/Tracker_Error.txt)

**Comment by DududeDude** [comment]
Myself and Edgeworth had a similar issue occurring. When I right-clicked something it produced an error on his end. The program would continue running if he clicked continue on the error, but what was on stream desynced on that particular item for me. Cycling through with left-clicks worked fine however.

The particular item I tried it on was the bottle for the bottom right runner. I don't have the error log handy unfortunately since the error did not happen on my end of things.

**Comment by Datyedyeguy** [comment]
Were both of you using the latest version? What layout was being used? Just want to be sure I can recreate and fix it for good.

**Comment by DududeDude** [comment]
Both of us were on 4.4.3, ffr.xml was being used.
